### ISSUE TITLE
Create an audit/diagnostics cron job

### ISSUE THREAD

**Issue by rdiaztushman** [dioscouri/f3-lib#73]
The cli script should set APP_NAME = audit
This allows our bootstraps to add preAudit, runAudit, and postAudit methods
Run this after initial installation, and it should create its own crontab entry if one doesn't exist (run every 5 minutes)

Should check for the existence of the process_queue.php long-running process, and if it doesn't exist, should start it.

Should likewise check for the existence of a the audit_queue_process long-running process, and if it doesn't exist, should start it.

**Comment by ChrisFrench** [comment]
I solved this very issue using upstart 

# Info
description "RSD Customers"
author      "Chris French"

# Events
start on startup
stop on shutdown

# Automatically respawn
respawn
respawn limit 20 5

# Run the script!
# Note, in this example, if your PHP script returns
# the string "ERROR", the daemon will stop itself.
script
    [ $(exec /usr/bin/php -f /var/www/rallysportdirect.com/cli/customers.php) = 'ERROR' ] && ( stop; exit 1; )
end script
